apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: crear-nodejs
  title: Servicio Node.js con Express
  description: Genera un servicio backend usando Cookiecutter y Express
spec:
  owner: equipo-backend
  type: service
  parameters:
    - title: Informaci칩n del proyecto
      required:
        - project_name
        - description
        - author
      properties:
        project_name:
          type: string
          title: Nombre del Proyecto
        description:
          type: string
          title: Descripci칩n
        author:
          type: string
          title: Autor
  steps:
    - id: generar
      name: Generar c칩digo con Cookiecutter
      action: cookiecutter:template
      input:
        url: "https://github.com/dcmaubm/Backstage_Demo/archive/refs/heads/template.zip"
        values:
          project_name: ${{ parameters.project_name }}
          description: ${{ parameters.description }}
          author: ${{ parameters.author }}

    - id: publicar
      name: Publicar en GitHub
      action: publish:github
      input:
        repoUrl: github.com/tu-org/${{ parameters.project_name }}
        defaultBranch: main
        description: ${{ parameters.description }}

    - id: registrar
      name: Registrar en el cat치logo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publicar'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
