apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - java
    - spring
    - maven
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
